### ISSUE TITLE
Create a Dockerfile for the Project

### ISSUE THREAD

**Issue by rishyym0927** [jinx-vi-0/BlogLog#21]
**Title:** Create a Dockerfile for the Project

**Description:**
We need to create a Dockerfile to containerize the project for easier deployment and consistency across different environments. The Dockerfile should:
- Set up the appropriate base image (e.g., `node:alpine` or `python:slim` depending on the tech stack).
- Install necessary dependencies.
- Copy the source code into the container.
- Expose the required port (if applicable).
- Define the entry point or command to run the application.

**Tasks:**
1. Choose an appropriate base image.
2. Install dependencies.
3. Copy source code.
4. Expose necessary ports.
5. Set up the entry point/command to run the application.

**Level:** GSSOC-EXT Level 3

**Assigned To:** @mention (or "To Be Assigned")

**Comment by khushiiagrawal** [comment]
@rishyym0927  i would like to work on making the docker file. Can you assign me this under GSSOC and hacktoberfest

**Comment by rishyym0927** [comment]
@jinx-vi-0  please assign this issue asap so that I can work on it or atleast tell me to update anything

**Comment by adarsh-site** [comment]
Assigned @rishyym0927

**Comment by geetanjalidubey9** [comment]
pls assign this task to me

**Comment by Suraj-kumar00** [comment]
Hi @jinx-vi-0, how have you been?
I would like to work on this issue as I'm proficient in `Cloud/DevOps` practices. If @rishyym0927 haven't given any progress I can:
1. Dockerize the project. 
2. Dockerize the project with `minimal docker image`.
3. Can Create a workflow to `build` and `push` the docker images to the `DockerHub Account` but for this I will need the credentials of your dockerhub account to push to docker image on your account.

Please assign this issue to me so that I can work on it.

**Comment by sharanikaa** [comment]
I would like to work on this, kindly assign me this issue.

**Comment by adarsh-site** [comment]
Any update @rishyym0927

**Comment by Ishita-Trivedi** [comment]
I would like to work on this, kindly assign me this issue.

**Comment by adarsh-site** [comment]
assigned @Ishita-Trivedi
